import { EMSAppShell } from '@/components/AppShell';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <EMSAppShell>
      <html lang="en">
        <body>{children}</body>
      </html>
    </EMSAppShell>
  )
}
